/**
 * All structured action types a mentor plan to-do point can represent.
 * These are intentionally aligned with the concrete tools the mentor agent can call.
 */
export const MENTOR_PLAN_TODO_ACTIONS = [
  "create_module",
  "create_node",
  "modify_node",
  "create_and_populate_module",
  "create_and_populate_node",
  "delete_node",
  "delete_module",
  "append_to_node",
  "edit_node_section",
] as const;

export type MentorPlanTodoAction = (typeof MENTOR_PLAN_TODO_ACTIONS)[number];

/**
 * A single to-do point in a mentor plan.
 * Each point should eventually involve at most one node (enforced by recursive decomposition).
 */
export interface MentorPlanTodoPoint {
  /** Human-readable description of the task */
  content: string;

  /**
   * Node IDs this point touches.
   * If more than one, the point will be recursively decomposed into sub-points.
   */
  nodeIds: string[];

  /**
   * Structured action type describing what this step will actually do.
   * Must be one of the supported values in MENTOR_PLAN_TODO_ACTIONS.
   */
  action: MentorPlanTodoAction;

  /**
   * Optional module this step is primarily about (for module-level operations).
   * For example, the module being created, deleted, or whose nodes are being edited.
   */
  moduleId?: string;

  /**
   * Optional primary node this step is about (for node-level operations).
   * This should be set when action operates on a single node.
   */
  nodeId?: string;

  /**
   * Short explanation of why this step exists or what it tries to achieve,
   * written for humans (mentors) to understand the intent behind the action.
   */
  explanation?: string;

  /**
   * Extra contextual notes that might help when executing this step,
   * e.g. summarized user intent, constraints, examples, or follow-up ideas.
   */
  contextNotes?: string;
}

/**
 * Plan generated by the orchestration agent for the AI mentor assistant.
 * Describes what the AI will do, with a flat to-do list where each point involves at most one node.
 */
export interface MentorPlan {
  /** High-level description of what the AI is going to do */
  description: string;
  /** To-do points, each involving at most one node */
  todoPoints: MentorPlanTodoPoint[];
}
